import { FileCheck2, GitCommitHorizontal, Workflow } from "lucide-react";
import { Link } from "wouter";
import { StatusBadge } from "@/components/StatusBadge";
import { trpc } from "@/lib/trpc";

export default function EvidenceLog() {
  const projects = trpc.controlCenter.projects.useQuery();
  const project = projects.data?.[0];
  const evidence = trpc.controlCenter.evidence.useQuery({ projectId: project?.id ?? 1 }, { enabled: Boolean(project) });
  return <div className="p-5 lg:p-8"><div className="border-b-[3px] border-black pb-7"><div className="text-[10px] font-black tracking-[0.16em] text-black/55">EXECUTION RECORD</div><h1 className="mt-2 flex items-center gap-4 text-5xl font-black tracking-[-0.09em] sm:text-7xl">EVIDENCE <FileCheck2 className="h-10 w-10 sm:h-14 sm:w-14" /></h1></div>{!project ? <div className="mt-8 border-[3px] border-black bg-black p-7 text-white"><div className="text-xl font-black">NO EVIDENCE WITHOUT A PROJECT.</div><Link href="/projects/new" className="mt-5 inline-block border-2 border-white px-3 py-2 text-xs font-black tracking-[0.1em] hover:bg-[var(--acid)] hover:text-black">REGISTER PROJECT</Link></div> : <div className="mt-8"><div className="mb-4 text-xs font-black tracking-[0.12em]">PROJECT / {project.name}</div>{evidence.data?.length ? <div className="divide-y-[3px] divide-black border-y-[3px] border-black">{evidence.data.map(item => <div key={item.id} className="grid gap-4 p-5 md:grid-cols-[auto_1fr_auto] md:items-center"><div className="text-3xl font-black tracking-[-0.08em]">{item.gateIndex.toString().padStart(2, "0")}</div><div><div className="font-mono text-xs font-bold break-all"><GitCommitHorizontal className="mr-2 inline h-4 w-4" />SHA / {item.sha}</div><div className="mt-2 text-xs font-bold text-black/60">BRANCH / {item.branch} · {new Date(item.receivedAt).toLocaleString()}</div><div className="mt-3 flex flex-wrap gap-2">{item.checks.map(check => <span key={check.name} className="border border-black px-2 py-1 text-[10px] font-black">{check.name} / {check.status}</span>)}</div></div><div className="flex items-center gap-3"><StatusBadge status={item.decision} />{item.workflowRunUrl ? <a href={item.workflowRunUrl} target="_blank" rel="noreferrer" className="border-2 border-black p-2 hover:bg-[var(--acid)]"><Workflow className="h-4 w-4" /></a> : null}</div></div>)}</div> : <div className="border-l-[5px] border-[var(--signal)] pl-4 text-sm font-bold">لم يتم استقبال Evidence بعد. استخدم POST /api/v1/evidence من GitHub Actions.</div>}</div>}</div>;
}
